language: python

services:
- docker
install:
- make deps
script:
- make lint
- make test
- make test_cov
- make test_xunit
- make test_complexity
- make docker_build
- make docker_push
deploy:
    provider: heroku
    app: maniek5k-app
    api_key: ${HEROKU_API_KEY}